### ISSUE TITLE
[btor2] Initialize array with scalar constant

### ISSUE THREAD

**Issue by ekiwi** [cristian-mattarei/CoSA#120]
The `btor2` format allows initializing arrays with scalar constants:
>  initializing a memory with a bit-vector constant zero, zero-initializes the whole memory
(src: https://link.springer.com/content/pdf/10.1007%2F978-3-319-96145-3_32.pdf)

CoSA fails to translate this simplified example (which works fine with `btormc`):
```
15 sort bitvec 2
26 sort bitvec 9
63 sort array 26 15
64 const 15 00
65 state 63 memory
66 init 63 65 64
```

The error message is:
```
pysmt.exceptions.PysmtTypeError: The formula '(memory = 0_2)' is not well-formed
```

**Comment by makaimann** [comment]
Thanks for pointing this out! Fixed with b5a1d6a838a1eeecbbd8ed6e60a2a85e841d437b. Just FYI, this isn't necessarily supported by every underlying SMT solver. For example, `boolector` just recently added public support for constant arrays, and that probably is not implemented in pysmt yet.
